### ISSUE TITLE
Questions about the MFCAD + + dataset

### ISSUE THREAD

**Issue by Corleone415** [whjdark/AAGNet#2]
Hello,
First of all, very nice work, congrats!
I have a question about the MFCAD + + data set here. You say that some STEP models in MFCAD + + have some topological errors and performed data cleaning. However, when I download according to the URL you provide, I find that there are still 59665 models in it. Can you provide the MFCAD + + data set after data cleaning ?
Thanks a lot and best regards!

**Comment by whjdark** [comment]
Thanks for your interest in our work.
You can use
`python -m dataset.crosscheck --dataset <MFCAD++ path>` 
to remove the data with problems.
Hope this can help you. 
Please let us know if you have any questions or suggestions.
