### ISSUE TITLE
anaconda 安装依赖的时候库冲突

### ISSUE THREAD

**Issue by hiktoop** [whjdark/AAGNet#3]
我在 anaconda 的环境中安装了你文档中列出的依赖，安装了 occt 和 pythonocc-core 7.5.1之后自动安装了 tbb 2020.2，但是后面安装 numba 的时候产生冲突（要求 tbb >= 2021），这个问题怎么解决，你在环境配置的时候是什么样的一个步骤？
后面我把 tbb 删除之后 occ 变成了最新的 7.7.2，之后可以安装 numba，但是运行的时候又报错了 occwl，这个安装不上去。

**Comment by KaboChow** [comment]
我也遇到同样的问题了，改为pip安装numba 就解决了
