### ISSUE TITLE
BUG report

### ISSUE THREAD

**Issue by CodingQinghao** [whjdark/AAGNet#8]
![image](https://github.com/user-attachments/assets/1b073de1-ad09-4755-9b5d-db41d3b388f0)

```
NonRationalBSplineEdgeAttribute 
RationalBSplineEdgeAttribute
```

These two features appeared twice.

**Comment by wll0307** [comment]
@CodingQinghao
你好，你的环境是手动下载的还是？，我想问几个问题1.要是我构建的数据，如何来获取每个文件的真实值 2.你想过就是把显示出来的加工特征信息弄成坐标的形式展现出来方便后期对零件进行加工，你有思路吗？我想跟您沟通一下

**Comment by whjdark** [comment]
Thanks for your issue, I have uploaded the fixed json file, removing the redundant input edge features. However, I did not directly replace the original json, because it could make the exported AAGraph and pretrained model unavailable and the redundant edge feature inputs have trivial effect on the final accuracy.

**Comment by whjdark** [comment]
> @CodingQinghao 你好，你的环境是手动下载的还是？，我想问几个问题1.要是我构建的数据，如何来获取每个文件的真实值 2.你想过就是把显示出来的加工特征信息弄成坐标的形式展现出来方便后期对零件进行加工，你有思路吗？我想跟您沟通一下

1、我建议手动安装每一个package，因为DGL2.2之后不再提供除linux系统以外的预编译包，occwl和pythonOCC因为源在外网很难直接拉去，建议使用镜像。
2、在我们的数据MFInstSeg中，标签（真实值）构造是自动的，对于每一个机加工制造特征，在参数化特征建模时候生成的新的面即是特征的几何（特征面），您可以参考这个方式构建具有特定特征的数据集进行训练，参考我们dataset文件夹下的README。对于其他的三维cad零件的标签（真实值）只能通过手动标注的方式得到。
3、无法理解加工特征的坐标的形式的具体意味，每个加工特征的几何是不一样的，由不同的特征面组合，如果您是想单纯获得每个特征的中心坐标，可以将每个特征面添加至一个包围盒（bbox），然后获取这个包围盒的中心。如果您想要获取每个特征的几何尺寸，比如一个slot的长宽高，或者一个blind hole的直径和深度 ... ，应该对每一类特征进行单独的处理，提取每类特征的几何尺寸。
4、如果您想将识别的特征用于CAM，这还有很长一段路要走，可以参考以下大致路径：识别特征->特征尺寸和PMI提取->特征工艺检索->工艺编排->刀路生成（这一部分可以参考NX的FBM）。实际上最后输入CAM后端的是特征几何的mesh（hole可是brep），可参考moduleworks。

**Comment by wll0307** [comment]
@whjdark 非常感谢您，我还有一个问题就是如果我想要在这24个lable标签上添加一些新的有标签数据，因为我看到这个标签有平面的跟非平面的，如何定义并添加到24个标签里面的。
